### ISSUE TITLE
Rewrite lightbox with bootstrap modals

### ISSUE THREAD

**Issue by nickserv** [wyantb/HashMask#10]
Edit: title used to be "Make clicking outside of the lightbox on the options page close it"

**Comment by wyantb** [comment]
Actually, probably have to rewrite it from scratch anyway, doesn't actually work in IE.  Could just use plan Bootstrap modals, probably.

**Comment by nickserv** [comment]
Good idea. If you want, you can assign me and I'll look into it.

**Comment by wyantb** [comment]
If you want to mess around, by all means, go ahead.

**Comment by nickserv** [comment]
Should I just put a carousel in a modal?
(see http://twitter.github.com/bootstrap/javascript.html)

**Comment by wyantb** [comment]
Yes, basically.  Really?  Fuck around until you've got something you like.  Fun fact: most of what I've been doing is just that.

Once done, we'll all take a look.

**Comment by nickserv** [comment]
This is mostly finished besides a couple of issues and incomplete bits, check out the carousel-examples branch.

EDIT: Actually, I also made a branch for getting this to work with modals alone. However, the carousel version does use one modal.

**Comment by wyantb** [comment]
I think the carousel-examples branch is fine.  Not sure why you used the class 'carousel-example' for something in our html, but w/e.  

Close if you're fine with it too.

**Comment by nickserv** [comment]
Ah, good point, I could have consolidated those two tags. And that id's there so different links can make our carousel do things. Closing issue.
