### ISSUE TITLE
Carousel doesn't loop properly

### ISSUE THREAD

**Issue by nickserv** [wyantb/HashMask#13]
Pressing the left and right buttons at either end of the carousel should cause it to loop to the other end, like it does in [Bootstrap's docs](http://twitter.github.com/bootstrap/javascript.html#carousel).

According to an issue on Bootstrap, this is a bug that was fixed in 2.0.2. We have 2.0.1.  When I try to update to a (custom, pre-compiled, and complete) version of Bootstrap 2.0.2, bootstrap-responsive.css vanishes, and for some reason the new Bootstrap.css won't load at all, leaving our options page pretty much broken.

How can we fix this? I would like some feedback on how we can safely upgrade to 2.0.2 (unless if you want to do it yourself).

**Comment by wyantb** [comment]
Updated to Bootstrap 2.0.2, now loops fine.

For future reference: I didn't make a custom download/installation of bootstrap, I just downloaded it from their main page.  I believe the two methods of getting Bootstrap are packaged differently.

Anyway, mind verifying that it's fine in master?

**Comment by nickserv** [comment]
Ah, odd, I thought the main download had LESS instead of CSS though. Did you compile it?

And yup, this is working, thanks.

**Comment by wyantb** [comment]
_shrug_ nope, main download doesn't seem to have LESS.

It's just this download: http://twitter.github.com/bootstrap/assets/bootstrap.zip
