### ISSUE TITLE
Get example images to always be in one row, even with smaller screens

### ISSUE THREAD

**Issue by nickserv** [wyantb/HashMask#16]

**Comment by wyantb** [comment]
Sure.  I hid it, lol.

**Comment by nickserv** [comment]
It's still possible to resize the window in such a way that everything is in one line except for the last image, and it doesn't hide the images in this case.

**Comment by wyantb** [comment]
Personally, I didn't mind this.  I just wanted to make sure we didn't go above two rows, which I did.  I'm not offended if you reopen this and want to mess with it.

**Comment by nickserv** [comment]
I made some commits to master, and now I'm using Bootstrap's built in grid system for fluid thumbnail arrangements. Is this good enough for me to close the issue? The images overlap a little when the window is smaller, but it's still fully usable. Also, it still shows the images on mobile devices.

**Comment by wyantb** [comment]
That's probably about the best behavior you could get out of it.  That said, it almost seems like the demo page should be an entirely separate page for mobile, since the popup modal doesn't really work out at all, at least on my Android.

**Comment by wyantb** [comment]
Stole & completed?
