### ISSUE TITLE
Make HashMask smaller (file size)

### ISSUE THREAD

**Issue by nickserv** [wyantb/HashMask#18]
Our master branch is 1.1 megabytes large (ignoring data in .git). That would all need to be downloaded in order for the extension to be installed. Also, this makes loading the preview page slower.
#### Tips
- Minify anything large that **isn't** ours (we should keep full versions of our own code, since this is an open source project)
- Remove unneeded images and libraries
- [Google Page Speed](https://developers.google.com/pagespeed/) might be helpful

**Edit 1**: DERP, I counted the .git directory by accident.
**Edit 2**: Removed jQuery dev, updating file sizes.

**Comment by wyantb** [comment]
I believe you're including, in that size, the .git directory, which users would not need download.  (Everything excluding .git is 1.2MB on my machine).

Still, a perfectly good TODO before alpha releasing.

**Comment by nickserv** [comment]
Here are the sizes of our directories, according to `du`:

```
~/Repos/hashmask master ✔ ➜ du --exclude .git
20K ./icons
12K ./doc
640K    ./img
20K ./bootstrap/img
52K ./bootstrap/js
112K    ./bootstrap/css
188K    ./bootstrap
40K ./src
8.0K    ./lib/img
148K    ./lib
1.1M    .
```

**Comment by nickserv** [comment]
And in reply to your comment, you're right. I have updated my post a few minutes ago.

**Comment by wyantb** [comment]
Looks fairly reasonable to me now.

https://www.dropbox.com/gallery/9648166/1/HashMask?h=a68bed

Lolol, look at the first image.  15/18 of my last emails are about this project.  Doin' it right.

**Comment by nickserv** [comment]
Not bad.

**Comment by nickserv** [comment]
Are we done here?

**Comment by wyantb** [comment]
I think so.  The only stuff Page Speed was complaining about were things I don't plan on messing with (especially, lots of server configuration stuff).
