### ISSUE TITLE
Carousel: tweak/remove animations so switching between different examples by clicking on their thumbnails is less derpy

### ISSUE THREAD

**Issue by nickserv** [wyantb/HashMask#21]
Click on an example. Close the modal. Click on another example. The previous example shows, then hides, and then the new example is shown. This should be more immediate, such as a fade out when a modal is closed and a fade in from an otherwise empty container when a modal is opened.

**Comment by wyantb** [comment]
You know, I'm not entirely sure this is possible with all the timing quirks.  How about we just kill the transitions and call it a day?  Check out master now.

**Comment by nickserv** [comment]
I think it's a lot better now, but it still shows the old image before the transition to open the new modal is fully complete. I understand that this is probably there because getting this animation stuff to time right is tricky. Should we ignore this? I think we should, if you can't think of an easy way to fix this.

**Comment by wyantb** [comment]
Finally addressed the issue, check out master sometime.  It was an issue I continually dismissed; jQuery not hiding things when the modal is hidden.  It probably starts at root, hits something that's display: none, and then proceeds to not care.  Just swapping the css directly (when the user clicks on one of the images, that is) is a much better approach.

**Comment by nickserv** [comment]
I'll close this, as it seems to be working pretty well.
