### ISSUE TITLE
Typing a password and waiting [time lapse] amount of time should only display the hashmask of the full string

### ISSUE THREAD

**Issue by nickserv** [wyantb/HashMask#22]
### What happens:

Set the time lapse to something like 1 second. Type really fast, and then stop. HashMask will blink between the hashmasks for every addition to the string before it finally displays, instead of just immediately showing the hash for the full string. (It displays the first character's hashmask, the first two characters' hashmask, the first three characters' hashmask, ....)
### What should happen:

It should show the latest hashmask only once after the time delay, even if multiple characters were typed before the delay.

Also, sorry for the terrible title. Feel free to make it nicer if you can think of anything.

**Comment by wyantb** [comment]
O.o.  Fail.  I thought it didn't do this...

**Comment by wyantb** [comment]
Alright, was due to a change I made a while back.  Should be good now.

**Comment by nickserv** [comment]
Also working, woo!
