### ISSUE TITLE
Consider setting a default time delay (other than 0)

### ISSUE THREAD

**Issue by nickserv** [wyantb/HashMask#23]

**Comment by wyantb** [comment]
I prefer this approach due to us having a salt.  Just my 2 cents.

**Comment by wyantb** [comment]
If someone else does want to change this, the two locations defaults are generated are in src/inject.js (when options.html is loaded not in a Chrome extension) and src/bg.js (when we are loaded in a Chrome extension).

Note that I am currently, explicitly setting this default to 0.

**Comment by nickserv** [comment]
Alright, cool. Well, I guess either way would be a good default, and this gives more immediate results. The time delay is there for people who need it, it's not like it's hard to turn on. I'll close this, though we might want to set at least a small default time delay in the future (if users seem to lean toward that).
