### ISSUE TITLE
Adding text to the end of a password (with a non-zero time delay) should hide the last hashmask until the time delay occurs again

### ISSUE THREAD

**Issue by nickserv** [wyantb/HashMask#24]
Type a password and wait for the delay. Then keep typing again. Your keypresses will not hide the previous hashmask.

If this feels like more of a matter of an opinion, feel free to elaborate.

**Comment by wyantb** [comment]
Sure it's opinion, but I like the idea anyway.  Will implement.

**Comment by wyantb** [comment]
Done.  Mind checking?

**Comment by nickserv** [comment]
It's working, thanks.
