### ISSUE TITLE
Disable HashMask Button

### ISSUE THREAD

**Issue by wyantb** [wyantb/HashMask#33]
In the top bar of chrome, add a button that temporarily disables HashMask for [the given domain | everything].  If someone's doing a screencast or something, it would be useful if there was a quick way to disable the hashmask before typing in their password (otherwise, an attacker with sufficient computing time/power could, eventually, grab that password, since they're not limited in # of requests to the server).

**Comment by nickserv** [comment]
I can finish this up if you want. I think part/most of it is already there, though in the end you can check on if you like how it looks or not.

**Comment by wyantb** [comment]
It's...not really most there at all.  The fundamentals, AKA hooking events up to the actual hashmasks on pages, is not there at all.  If you want to take a crack at it, by all means, just you'd have to fire off the events, register to them, etc.

Also, I was going to make the popup page different after all.  If you've installed the Page Speed addon, I want to do a few things with our button like that.  Popup a big page with big bold ON/OFF text, yes.  But also, remind people what's up with the salt, and some other stuff.
