### ISSUE TITLE
Modals are broken

### ISSUE THREAD

**Issue by nickserv** [wyantb/HashMask#35]
Trying to show a modal results in one of these errors in Chrome's JavaScript console:
`Refused to execute inline event handler because of Content-Security-Policy.`

This might be an issue with switching to manifest version 2. However, we should try to stick with the current standard manifest format and try to fix this issue, rather than reverting the manifest back.

**Comment by wyantb** [comment]
Not just modals.  See save button, probably restore buttons and everything else too.

**Comment by wyantb** [comment]
As a nifty reference, see: http://code.google.com/chrome/extensions/contentSecurityPolicy.html

**Comment by wyantb** [comment]
Ignore my first comment; the salt and hash buttons work fine now.  Only the modals are still broken.

**Comment by nickserv** [comment]
I've done part of this but just haven't gotten around to finishing it yet. I'll have time early tonight, so I can finish this then.
