### ISSUE TITLE
I don't believe these are password fields

### ISSUE THREAD

**Issue by kristenmills** [wyantb/HashMask#36]
![herp derp](http://i.imgur.com/bzzix.jpg)
![herp derp](http://i.imgur.com/if0f7.png)

**Comment by wyantb** [comment]
Huh...tried out those sites relatively quickly, I didn't notice the same problem.  Version 1.0 or 1.1?

**Comment by kristenmills** [comment]
1.1

**Comment by wyantb** [comment]
With a Mac, I take it.  Last question, I think, at least for now: any chance that you have an addon, some settings, or w/e, such that you autofill the password fields as soon as you load up these sites?

**Comment by nickserv** [comment]
I'm not having either of this issues myself (even if I log into Kongregate). I'm on Arch Linux with Chromium 18.0.

**Comment by nickserv** [comment]
Also, Kristen, are you running a stable version of Chrome?

**Comment by kristenmills** [comment]
stable version of chrome: correct (18)
With kongregate at least, when i removed the password from my keychain and logged in, the password no longer appeared up top after i logged in.  I'm assuming it will be a similar situation with photobucket but nobody uses photobucket.

**Comment by deriachai** [comment]
Mac Keychain issue maybe?

**Comment by nickserv** [comment]
Kristen, what if you use Kongregate/Photobucket in incognito mode? Same issue? Also please try it with and without logging in.

**Comment by wyantb** [comment]
Nick, I'm with Dan on this one, it's likely a keychain-style issue.  In fact, I noticed this kind of thing happening, I believe with Twitter, before I did the on focus type stuff.  

Unless you or Dan plans on trying to fix this one, I've got enough data to work on it for now.

Fun issue, only wish the things I put in place already would've handle it, too sad ^^

**Comment by kristenmills** [comment]
I have come to a conclusion.  Nick and I noticed that when using the photobucket and kongregate password fields without saved info, hashmask doesn't actually appear there. What I think it is, is that when the password is retrieved from my keychain, hashmask is like PASSWORD APPEARED I MUST HASHMASK A PASSWORD FIELD and then it can't find it so it just puts it somewhere.

**Comment by nickserv** [comment]
The other weird part is that normally (not on a Mac), HashMask won't appear on the password fields of Photo Bucket or Kongregate at all. They are input fields of the type password, too. Kristen thinks it might be because the Photo Bucket and Konregate password fields have classes, though I feel like jQuery wouldn't have an issue with this.

**Comment by wyantb** [comment]
Kristen, would you be able to try out this version to see if it addresses the issue?  

https://github.com/wyantb/HashMask/raw/master/builds/hashmask-1.1.hotfix.crx

**Comment by wyantb** [comment]
Confirmed fix.  Thanks!
