### ISSUE TITLE
HaskMask is logging to my console

### ISSUE THREAD

**Issue by geowa4** [wyantb/HashMask#45]
With the new update, I am getting two things logged to my console: "HashMask received message" and an Object that appears to be for settings.

Version 21.0.1171.0 dev

**Comment by wyantb** [comment]
You'd be correct.  I'll remove that by tomorrow, in case there's any other problems.

**Comment by geowa4** [comment]
Perusing through the source and there are a lot of `console.log` calls.

**Comment by wyantb** [comment]
Quite.  Actually, Chrome is cool with version numbers with three digits, so I'm taking care of this one now.

**Comment by wyantb** [comment]
There we go.  1.2.1, removed all the console calls (most importantly, the ones on inject.js, the ones people actually see).  Can we forget this happened now?  Just embarrassing.

**Comment by geowa4** [comment]
i'll forget it once i stop seeing it :-P
