### ISSUE TITLE
Changelog in gh-pages?

### ISSUE THREAD

**Issue by nickserv** [wyantb/HashMask#46]
We have a Changes.md file. Should I convert it to an HTML page for gh-pages?

Current Status: added Changes.md to gh-pages branch, no links to it on HTML pages yet

**Comment by wyantb** [comment]
I don't think we have any strong need to change Changes.md.  The format is dead simple and works, you know?  Unless I'd have to put down a riot to keep it from changing, I won't bother changing my ways.  I can and do already link to it, and update it, easily enough as is.  So, vetoing.

**Comment by nickserv** [comment]
Do we want to keep it in gh-pages, though? I'm working on a merge commit where I'm going to add it there, unless that's not needed.

**Comment by wyantb** [comment]
I've been linking to the version in master.  So no, we don't need it.  Just one version in one branch is fine.

In any case, we'll get to merge hell eventually once FF is done anyway.  So...yeah.
