### ISSUE TITLE
HashMask does not display at all

### ISSUE THREAD

**Issue by nickserv** [wyantb/HashMask#8]
Since commit 46acfde061254fc6d01231803bdd3411514e355f, HashMask is not displayed at all on the options page and on other sites.

**Comment by wyantb** [comment]
Pff, what kind of bum writes code like that?

Anyway, addressed, mind verifying?

**Comment by nickserv** [comment]
To be honest, I'm not sure exactly what's causing it. I think it's the inject script (which you changed on this commit), since it doesn't work on the options page either.

**Comment by wyantb** [comment]
Nope, this change.

https://github.com/wyantb/HashMask/commit/09c8a7fb55bdf14b65d54ba072eebc46406a9c71

bg.js knows nothing of hashmask, so it can't muck with the settings.  

In any case...does it work for you again?

**Comment by nickserv** [comment]
Wooo, it works. Thanks!
